# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('group_introduction', models.CharField(default='无', max_length=100)),
                ('group_establish_date', models.DateField(auto_now=True)),
                ('group_update_date', models.DateField(auto_now_add=True)),
                ('group_is_public', models.BooleanField()),
                ('group_max_member', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.CharField(max_length=20)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.Group')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=30)),
                ('school_province', models.CharField(max_length=20)),
                ('school_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('stu_id', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=15)),
                ('realname', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2)),
                ('birthday', models.DateField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=30)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.School')),
            ],
        ),
        migrations.AddField(
            model_name='group_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.User'),
        ),
    ]
