# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheTime',
        ),
        migrations.AlterField(
            model_name='group_user',
            name='privilege',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(),
        ),
    ]
