# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_auto_20170510_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveAffair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.Affairs')),
            ],
        ),
        migrations.CreateModel(
            name='InGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.Group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.Group_User')),
            ],
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_province',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_updatetime',
            new_name='updatetime',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ingroup',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.User'),
        ),
        migrations.AddField(
            model_name='haveaffair',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.User'),
        ),
    ]
