# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0003_auto_20170427_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_user',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='group_user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='Resource.User'),
        ),
        migrations.DeleteModel(
            name='Group_User',
        ),
    ]
