# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0007_group_user_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_user',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
